project_id = "kiyirgmbdtwnedrnoooh"

[functions.fetch-sales-data]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.process-insights]
verify_jwt = false

[functions.evolution-get-qrcode]
verify_jwt = false

[functions.evolution-check-status]
verify_jwt = false